version: '3.8'

services:
  task-service-migrate:
    depends_on:
      - db
    build: ./src/task-service
    networks:
      - taskservice
    env_file: .env
    command: ["migration", "migrate"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  task-service-grpc:
    depends_on:
      - db
    build: ./src/task-service
    ports:
      - 9090:9090
    networks:
      - taskservice
    env_file: .env
    command: ["serve", "grpc"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  task-service-http:
    depends_on:
      - db
    build: ./src/task-service
    ports:
      - 9091:9091
    networks:
      - taskservice
    env_file: .env
    command: ["serve", "http"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  authen-go-migrate:
    depends_on:
      - db
    build: ./src/authen-go
    networks:
      - taskservice
    env_file: .env
    command: ["migration", "migrate"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  authen-go-grpc:
    depends_on:
      - db
    build: ./src/authen-go
    ports:
      - 8080:8080
    networks:
      - taskservice
    env_file: .env
    command: ["serve", "grpc"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  authen-go-http:
    depends_on:
      - db
    build: ./src/authen-go
    ports:
      - 8081:8081
    networks:
      - taskservice
    env_file: .env
    command: ["serve", "http"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  db:
    image: bitnami/mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - taskservice
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    labels:
      co.elastic.logs/enabled: false

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

networks:
  taskservice:
