apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: app-ns
spec:
  storageClassName: "vultr-block-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi